name: flutter_facebook_app_links
description: A Flutter plugin to catch deferred deep links from Facebbok ads with FB App Links SDK.
version: 3.0.1+7
homepage: https://github.com/Mapk26/flutter_facebook_app_links

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: it.remedia.flutter_facebook_app_links
        pluginClass: FlutterFacebookAppLinksPlugin
      ios:
        pluginClass: FlutterFacebookAppLinksPlugin

